name: fmri_connectomes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - conda-forge::nibabel
  - numpy=1.26.*
  - pandas=2.1.*
  - antspyx=0.4.2
  - begins==0.9
  - Cython==3.0.6
  - dcor==0.6
  - dill==0.3.7
  - dipy==1.7.0
  - fury==0.9.0
  - matplotlib==3.8.1
  - nibabel==5.1.0
  - nipype==1.8.6
  - numpy==1.26.2
  - opencv_python==4.8.1.78
  - openpyxl==3.1.2
  - pandas==2.2.1
  - paramiko==3.3.1
  - scikit_image==0.22.0
  - scikit_learn==1.3.2
  - scipy==1.11.3
  - setuptools==58.1.0
  - vtk==9.3.0
  - xlrd==2.0.1
  - XlsxWriter==3.1.9