name: fmri_connectomes
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - conda-forge::nibabel=5.1.0
  - numpy=1.26.*
  - begins=0.9
  - Cython=3.0.6
  - dcor=0.6
  - dill=0.3.7
  - dipy=1.7.0
  - matplotlib=3.8.1
  - nipype=1.8.6
  - numpy=1.26.2
  - opencv=4.8.1
  - openpyxl=3.1.2
  - pandas=2.2.1
  - paramiko=3.3.1
  - scikit-image=0.22.0
  - scikit-learn=1.3.2
  - scipy=1.11.3    
  - vtk=9.3.0
  - xlrd=2.0.1
  - XlsxWriter=3.1.9
  - pip:
    - antspyx==0.4.2
    - fury==0.9.0